// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: pkg/pb/manga.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author        string  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PublishedDate string  `protobuf:"bytes,4,opt,name=published_date,json=publishedDate,proto3" json:"published_date,omitempty"`
	Genre         string  `protobuf:"bytes,5,opt,name=genre,proto3" json:"genre,omitempty"`
	Price         float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int64   `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	Description   string  `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Rating        float64 `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_pkg_pb_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Manga) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetPublishedDate() string {
	if x != nil {
		return x.PublishedDate
	}
	return ""
}

func (x *Manga) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Manga) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Manga) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type GetMangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMangaRequest) Reset() {
	*x = GetMangaRequest{}
	mi := &file_pkg_pb_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaRequest) ProtoMessage() {}

func (x *GetMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaRequest.ProtoReflect.Descriptor instead.
func (*GetMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{1}
}

func (x *GetMangaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Manga  *Manga `protobuf:"bytes,2,opt,name=manga,proto3" json:"manga,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetMangaResponse) Reset() {
	*x = GetMangaResponse{}
	mi := &file_pkg_pb_manga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMangaResponse) ProtoMessage() {}

func (x *GetMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMangaResponse.ProtoReflect.Descriptor instead.
func (*GetMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{2}
}

func (x *GetMangaResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *GetMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListMangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genre  string `protobuf:"bytes,1,opt,name=genre,proto3" json:"genre,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *ListMangaRequest) Reset() {
	*x = ListMangaRequest{}
	mi := &file_pkg_pb_manga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaRequest) ProtoMessage() {}

func (x *ListMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaRequest.ProtoReflect.Descriptor instead.
func (*ListMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{3}
}

func (x *ListMangaRequest) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *ListMangaRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ListMangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Manga  []*Manga `protobuf:"bytes,2,rep,name=manga,proto3" json:"manga,omitempty"`
	Error  string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ListMangaResponse) Reset() {
	*x = ListMangaResponse{}
	mi := &file_pkg_pb_manga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangaResponse) ProtoMessage() {}

func (x *ListMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangaResponse.ProtoReflect.Descriptor instead.
func (*ListMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{4}
}

func (x *ListMangaResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListMangaResponse) GetManga() []*Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *ListMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateMangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manga *Manga `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
}

func (x *CreateMangaRequest) Reset() {
	*x = CreateMangaRequest{}
	mi := &file_pkg_pb_manga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMangaRequest) ProtoMessage() {}

func (x *CreateMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMangaRequest.ProtoReflect.Descriptor instead.
func (*CreateMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMangaRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type CreateMangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Manga  *Manga `protobuf:"bytes,2,opt,name=manga,proto3" json:"manga,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CreateMangaResponse) Reset() {
	*x = CreateMangaResponse{}
	mi := &file_pkg_pb_manga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMangaResponse) ProtoMessage() {}

func (x *CreateMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMangaResponse.ProtoReflect.Descriptor instead.
func (*CreateMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMangaResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *CreateMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateMangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manga *Manga `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
}

func (x *UpdateMangaRequest) Reset() {
	*x = UpdateMangaRequest{}
	mi := &file_pkg_pb_manga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMangaRequest) ProtoMessage() {}

func (x *UpdateMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMangaRequest.ProtoReflect.Descriptor instead.
func (*UpdateMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateMangaRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type UpdateMangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Manga  *Manga `protobuf:"bytes,2,opt,name=manga,proto3" json:"manga,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *UpdateMangaResponse) Reset() {
	*x = UpdateMangaResponse{}
	mi := &file_pkg_pb_manga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMangaResponse) ProtoMessage() {}

func (x *UpdateMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMangaResponse.ProtoReflect.Descriptor instead.
func (*UpdateMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMangaResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateMangaResponse) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

func (x *UpdateMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteMangaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMangaRequest) Reset() {
	*x = DeleteMangaRequest{}
	mi := &file_pkg_pb_manga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMangaRequest) ProtoMessage() {}

func (x *DeleteMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMangaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMangaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMangaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int64  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteMangaResponse) Reset() {
	*x = DeleteMangaResponse{}
	mi := &file_pkg_pb_manga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMangaResponse) ProtoMessage() {}

func (x *DeleteMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_manga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMangaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_manga_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMangaResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeleteMangaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_pb_manga_proto protoreflect.FileDescriptor

var file_pkg_pb_manga_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x22, 0xe6, 0x01, 0x0a, 0x05,
	0x4d, 0x61, 0x6e, 0x67, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x61,
	0x74, 0x69, 0x6e, 0x67, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x67, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x61,
	0x6e, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61,
	0x52, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x40, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22,
	0x65, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x05,
	0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61,
	0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05,
	0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61,
	0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61,
	0x22, 0x67, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x22, 0x0a, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x05, 0x6d, 0x61,
	0x6e, 0x67, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x12, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x22, 0x0a, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x05, 0x6d, 0x61,
	0x6e, 0x67, 0x61, 0x22, 0x67, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e,
	0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52,
	0x05, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x5d, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0xdd, 0x02, 0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67,
	0x61, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d,
	0x61, 0x6e, 0x67, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6e, 0x67, 0x61, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d,
	0x61, 0x6e, 0x67, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x6e,
	0x67, 0x61, 0x12, 0x17, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6d, 0x61,
	0x6e, 0x67, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x6e, 0x67, 0x61, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x6e, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x6e,
	0x67, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x67, 0x61, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_manga_proto_rawDescOnce sync.Once
	file_pkg_pb_manga_proto_rawDescData = file_pkg_pb_manga_proto_rawDesc
)

func file_pkg_pb_manga_proto_rawDescGZIP() []byte {
	file_pkg_pb_manga_proto_rawDescOnce.Do(func() {
		file_pkg_pb_manga_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_manga_proto_rawDescData)
	})
	return file_pkg_pb_manga_proto_rawDescData
}

var file_pkg_pb_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_pb_manga_proto_goTypes = []any{
	(*Manga)(nil),               // 0: manga.Manga
	(*GetMangaRequest)(nil),     // 1: manga.GetMangaRequest
	(*GetMangaResponse)(nil),    // 2: manga.GetMangaResponse
	(*ListMangaRequest)(nil),    // 3: manga.ListMangaRequest
	(*ListMangaResponse)(nil),   // 4: manga.ListMangaResponse
	(*CreateMangaRequest)(nil),  // 5: manga.CreateMangaRequest
	(*CreateMangaResponse)(nil), // 6: manga.CreateMangaResponse
	(*UpdateMangaRequest)(nil),  // 7: manga.UpdateMangaRequest
	(*UpdateMangaResponse)(nil), // 8: manga.UpdateMangaResponse
	(*DeleteMangaRequest)(nil),  // 9: manga.DeleteMangaRequest
	(*DeleteMangaResponse)(nil), // 10: manga.DeleteMangaResponse
}
var file_pkg_pb_manga_proto_depIdxs = []int32{
	0,  // 0: manga.GetMangaResponse.manga:type_name -> manga.Manga
	0,  // 1: manga.ListMangaResponse.manga:type_name -> manga.Manga
	0,  // 2: manga.CreateMangaRequest.manga:type_name -> manga.Manga
	0,  // 3: manga.CreateMangaResponse.manga:type_name -> manga.Manga
	0,  // 4: manga.UpdateMangaRequest.manga:type_name -> manga.Manga
	0,  // 5: manga.UpdateMangaResponse.manga:type_name -> manga.Manga
	5,  // 6: manga.MangaService.CreateManga:input_type -> manga.CreateMangaRequest
	1,  // 7: manga.MangaService.GetManga:input_type -> manga.GetMangaRequest
	3,  // 8: manga.MangaService.ListManga:input_type -> manga.ListMangaRequest
	7,  // 9: manga.MangaService.UpdateManga:input_type -> manga.UpdateMangaRequest
	9,  // 10: manga.MangaService.DeleteManga:input_type -> manga.DeleteMangaRequest
	6,  // 11: manga.MangaService.CreateManga:output_type -> manga.CreateMangaResponse
	2,  // 12: manga.MangaService.GetManga:output_type -> manga.GetMangaResponse
	4,  // 13: manga.MangaService.ListManga:output_type -> manga.ListMangaResponse
	8,  // 14: manga.MangaService.UpdateManga:output_type -> manga.UpdateMangaResponse
	10, // 15: manga.MangaService.DeleteManga:output_type -> manga.DeleteMangaResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_pb_manga_proto_init() }
func file_pkg_pb_manga_proto_init() {
	if File_pkg_pb_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_manga_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_manga_proto_goTypes,
		DependencyIndexes: file_pkg_pb_manga_proto_depIdxs,
		MessageInfos:      file_pkg_pb_manga_proto_msgTypes,
	}.Build()
	File_pkg_pb_manga_proto = out.File
	file_pkg_pb_manga_proto_rawDesc = nil
	file_pkg_pb_manga_proto_goTypes = nil
	file_pkg_pb_manga_proto_depIdxs = nil
}
